#!/usr/bin/php
<?php  // not necessary, I just don't want the code to show up in the shell

/**
 *  Notes:
 *
 * I'm not too much for putting php into a bash script, but I didn't want to deviate from the instructions in any way.
 *
 * I think that there are a lot of good approaches to the problem, but stuck to a simple procedural style due
 * to the brevity of the problem.
 *
 * The points have no ordering rules listed in the spec, so I just used an ordering that generates the expected outcome 
 * (that is, parses them left to right, top to bottom).  It would be possible to generate a different path set if 
 * you, say, reversed or randomize the order of the points.
 *
 * There is no validation for the map: the program assumes all lines are equal length.  As such, the program breaks if
 * the lines are unequal length.  We could either invalidate the map and thorw an error,  or we could write code that 
 * expands the map areas not listed in input file (given the nature of arrays in PHP all we'd do is to make sure that 
 * the path drawing code pushes newline characters to the end of a line's array).
 *
 * The xy coordinate convention is inverted in this code, as it is easier to keep xy straight in my head, even if 
 * the actual map is yx graphically.
 *
 * The program will overwrite an existing output file
 *
 * I don't do any error handling with the file write at all, or much error checking at all.
 *
 *  Adding some way of easily expanding the test runner in path-problem.sh would be an easy thing to do and simplify adding test cases.
 *
 */

/**
 *  Environment
 *
 */

define('POINT_CHAR', "#");
define('PATH_CHAR', "*");

/**
 *  Program Logic
 *
 */

// get the files and verify that the input exists:
$fileName_in = $argv[1];
$fileName_out = $argv[2];
if (!file_exists ($fileName_in)) {
    echo "bad input file: $fileName_in";
    die();
}

// load the file into an array:
$map = fileToArray($fileName_in);

// find the points:
$points = findPoints($map);

// draw paths between each point:
for($pathIndex = 1; $pathIndex < count($points); $pathIndex++ ) {
    $map = drawPathBetweenPoints($points[$pathIndex - 1], $points[$pathIndex], $map);
}

// output the array as a file:
arrayToFile($fileName_out, $map);
die();

// end //

/**
 *  Helper functions
 *
 */

/**
 * read a file's cahracters into a 2d array
 * @param $fileName_in
 *
 * @return array
 */
function fileToArray($fileName_in) {

    $output = array();
    $fh = fopen($fileName_in, "r");

    while (!feof($fh)) {
        $line = fgets($fh);
        $output[] = str_split($line);
    }

    fclose($fh);

    return $output;

}

/**
 * writes a 2d map array to a file.
 * @param $fileName_out = the output of the file name
 * @param $map
 *
 * no error checking
 *
 */
function arrayToFile($fileName_out, $map) {

    $fh = fopen($fileName_out, "w");

    foreach ($map as $line) {
        fputs($fh, implode("", $line));
    }

    fclose($fh);
}

/**
 * searches left to right and top to bottom to generate a list of points on the map array
 *
 * @param $map - the 2d map array
 *
 * @return array - a list of arrays with x and y indexes for each point
 */
function findPoints ($map) {
    $out = array();

    foreach ($map as $x => $line) {
        foreach($line as $y => $element) {
            if ($element == POINT_CHAR) {
                $out[] = array("x" => $x, "y" => $y);
            }
        }
    }
    return $out;
}

/**
 * draws a path on the map array
 * @param $start - starting point consisting of an array with keys for x and y
 * @param $end - ending point consisting of an array with keys for x and y
 * @param $map - the 2d map array
 *
 * @return array - the modified map
 */
function drawPathBetweenPoints($start, $end, $map) {

    // draw the vert:
    $y = $start['y'];
    for ($x = min($start['x'], $end['x']) + 1; $x <= max($start['x'], $end['x']); $x++) {
        $map[$x][$y] = PATH_CHAR;
    }

    // draw the horz:
    $x--;
    for ($y = min($start['y'], $end['y']) + 1; $y < max($start['y'], $end['y']); $y++) {
        $map[$x][$y] = PATH_CHAR;
    }

    return $map;
}
